control:
  build: ./env
  hostname: control
  links:
    - lb01
    - app01
    - app02
    - db01
  ports:
    - "2200:22"
  volumes:
    - ./:/work
lb01:
  build: ./env
  hostname: lb01
  links:
    - app01
    - app02
  ports:
    - "2201:22"
    - "8001:80"
app01:
  build: ./env
  hostname: app01
  links:
    - db01
  ports:
    - "2211:22"
    - "8081:80"
app02:
  build: ./env
  hostname: app02
  links:
    - db01
  ports:
    - "2212:22"
    - "8082:80"
db01:
  build: ./env
  hostname: db01
  ports:
    - "2222:22"
    - "3306:3306"
