Vagrant.configure("2") do |config|
      config.vm.define "host" do | server |
        server.vm.box = "generic/ubuntu2004"
        server.vm.hostname = "host"
        server.vm.network "private_network", ip: "192.168.137.11"
      end
end