Vagrant.configure("2") do |config|
    ## 2 web VMs 
    (1..2).each do |i|
      config.vm.define "web0#{i}" do | web |
        web.vm.box = "generic/centos8"
        web.vm.network "private_network", ip: "192.168.137.11#{i}"
      end
    end 
  
    ## 2 centos VMs
    (1..2).each do |i|
      config.vm.define "db0#{i}" do | db |
        db.vm.box = "generic/centos8"
        db.vm.network "private_network", ip: "192.168.137.12#{i}"
      end
    end
    config.vm.provision "shell", path: "provision.sh"
    # Hyper-V Specific Configuration
    config.vm.provider "hyperv" do |h|
        h.linked_clone = true
    end
  end