- name: Ensure web servers are gone 
  hosts: localhost
  tasks:
  - name: Ensure container is absent 
    docker_container:
      name: "{{ item }}"
      container_default_behavior: compatibility 
      force_kill: yes
      state: absent 
    loop: "{{ query('inventory_hostnames', 'web_servers') }}"

- name: Ensure db servers are gone 
  hosts: localhost
  tasks:
  - name: Ensure container is absent 
    docker_container:
      name: "{{ item }}"
      container_default_behavior: compatibility 
      force_kill: yes
      state: absent 
    loop: "{{ query('inventory_hostnames', 'db_servers') }}"