---
- hosts: all
  become: true
  tasks:
    - name: Ensure chrony is installed
      ansible.builtin.yum:
        name: chrony
        state: present

    - name: Ensure chrony is installed (without changed_when always reports changed)
      ansible.builtin.shell: |
        set -o pipefail
        if ! rpm -qa | grep -qw chrony; then
          yum install -y chrony
        fi
      changed_when: false

    - name: Ensure chrony is running
      ansible.builtin.service:
        name: chronyd
        state: started
        enabled: true
