---
- hosts: all
  become: yes
  tasks:
    - name: Ensure NTP is installed
      ansible.builtin.yum: name=ntp state=present

    - name: Ensure NTP is installed (always reports changed)
      ansible.builtin.shell: |
        if ! rpm -qa | grep -qw ntp; then
          yum install -y ntp
        fi

    - name: Ensure NTP is running
      ansible.builtin.service: name=ntpd state=started enabled=yes
