---
- hosts: database
  become: yes
  tasks:
    - name: install mysql-server
      ansible.builtin.apt: name=mysql-server state=present update_cache=yes

    - name: ensure mysql started
      ansible.builtin.service: name=mysql state=started enabled=yes

    - name: ensure mysql listening on all ports
      ansible.builtin.lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf regexp=^bind-address
                                  line="bind-address            = 0.0.0.0"
      notify: restart mysql

  handlers:
    - name: restart mysql
      ansible.builtin.service: name=mysql state=restarted