---
- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: update apt cache
      ansible.builtin.apt: update_cache=yes cache_valid_time=86400
      tags: [ 'packages' ]

- include: control.yml
- include: database.yml
- include: webserver.yml
- include: loadbalancer.yml