---
- hosts: webserver
  become: yes
  tasks:
    - name: install web components
      ansible.builtin.apt: name="{{ item }}" state=present update_cache=yes
      with_items:
        - apache2
        - libapache2-mod-wsgi
        - python3-pip
        - python3-virtualenv

    - name: ensure apache2 started
      ansible.builtin.service: name=apache2 state=started enabled=yes

    - name: ensure mod_wsgi enabled
      community.general.apache2_module: name=wsgi state=present
      notify: restart apache2

  handlers:
    - name: restart apache2
      ansible.builtin.service: name=apache2 state=restarted