---
- name: Install Apache.
  hosts: all
  become: true

  handlers:
    - import_tasks: handlers/apache.yml

  pre_tasks:
    - name: Update apt cache if needed.
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Load variable files.
      include_vars: "{{ item  }}"
      with_first_found:
        - "vars/apache_{{ ansible_os_family | lower }}.yml"
        - "vars/apache_default.yml"

  tasks:
    - import_tasks: tasks/apache.yml
