#!/bin/sh

# Loads private keys generated by vagrant
# Running ssh-agent is required
# Keys can be verified using ssh-add -l

for IdentityFile in $(vagrant ssh-config | grep IdentityFile | cut -d" " -f4)
do
    ssh-add ${IdentityFile}
done