---
# ansible -m copy -a "src=../adhoc/master.gitconfig dest=~/.gitconfig" localhost

- name: Configure git and install packages
  hosts: localhost
  tasks:
  - name: Ensure ~/.gitconfig copied from master.gitconfig
    ansible.builtin.copy:
      src: "../adhoc/master.gitconfig"
      dest: "~/.gitconfig"
  
  - name: Ensure homebrew packages are installed
    community.general.homebrew:
      name: [
        'bat',
        'jq'
      ]
      state: present
      update_homebrew: yes